name: "Test"
on:
  pull_request:

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check

  test-image:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        crossSystem:
          - '{ config = "x86_64-unknown-linux-musl"; useLLVM = true; isStatic = true;  }'

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-cross-overlay

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: "Build docker image"
        run: ./scripts/build_docker_image.sh
